### ISSUE TITLE
Nuget package requires authentication. Unable to download

### ISSUE THREAD

**Issue by ExperimentsAndIdeas** [Microsoft/healthvault-samples#21]
VS2017 preview for Windows comes up with a non-stop authentication box that never goes away (product bug) when restoring the package for Xamarin.  That should be filed somewhere.

Also, when I open using Visual Studio (not code edition) on Mac, I see that the server below is prompting me. microsofthealth.pkgs.visualstudio.com.

I'm unable to manually install the DLL, since the health website only links me to the nuget package.

**Comment by dimitrijevic** [comment]
It should be easily fixed if you go into the manage packages for solution and switch the package source to "nuget.org" instead of the "health nightly packages", they published the newer prerelease nugets there in the meantime, however those version seem to have to be updated to using ActionPlanInstanceV2...I'll do a pull request to change that...if they accept it should fix ActionPlansViewModel.cs

**Comment by davidkwoods** [comment]
With the Pull Request completed, the reliance on a non-public feed is now fixed.
